/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeBindings */

#ifndef _Included_NativeBindings
#define _Included_NativeBindings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeBindings
 * Method:    JS_NewRuntime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_NativeBindings_JS_1NewRuntime
  (JNIEnv *, jclass);

/*
 * Class:     NativeBindings
 * Method:    JS_FreeRuntime
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_NativeBindings_JS_1FreeRuntime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     NativeBindings
 * Method:    JS_SetRuntimeInfo
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_NativeBindings_JS_1SetRuntimeInfo
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     NativeBindings
 * Method:    JS_SetMemoryLimit
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_NativeBindings_JS_1SetMemoryLimit
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     NativeBindings
 * Method:    JS_SetGCThreshold
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_NativeBindings_JS_1SetGCThreshold
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     NativeBindings
 * Method:    JS_SetMaxStackSize
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_NativeBindings_JS_1SetMaxStackSize
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     NativeBindings
 * Method:    JS_NewContext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_NativeBindings_JS_1NewContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     NativeBindings
 * Method:    JS_FreeContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_NativeBindings_JS_1FreeContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     NativeBindings
 * Method:    JS_Eval
 * Signature: (JLjava/lang/String;Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_NativeBindings_JS_1Eval
  (JNIEnv *, jclass, jlong, jstring, jstring, jint);

/*
 * Class:     NativeBindings
 * Method:    JS_ToFloat64
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_NativeBindings_JS_1ToFloat64
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     NativeBindings
 * Method:    JS_ToInt64
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_NativeBindings_JS_1ToInt64
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     NativeBindings
 * Method:    JS_ToInt32
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_NativeBindings_JS_1ToInt32
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     NativeBindings
 * Method:    JS_ToTag
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_NativeBindings_JS_1ToTag
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
